version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/frontend-a"
    target-branch: "develop/a"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/packages/frontend-b"
    target-branch: "develop/b"
    schedule:
      interval: "daily"
